### ISSUE TITLE
No Firebase App '[DEFAULT]' has been created - I don't what actually creating the issue and how it can be solved - kindly help me .

### ISSUE THREAD

**Issue by saqlainIBA** [angular/angularfire2#1105]
Hello everyone ! i am new in ionic and basically when i started working on uploading storing images and when i ionic serve this project it works fine but when i click to that particular page where i had to upload images it gives me an error - image is attached below .
![error](https://user-images.githubusercontent.com/18227705/29238141-6511451c-7ee3-11e7-86cc-530a89d83445.PNG)

this is my page typescript .
![paid ts](https://user-images.githubusercontent.com/18227705/29238144-74941a0a-7ee3-11e7-8776-b36cfe728c47.PNG)

this is my app.module.ts
![app module ts](https://user-images.githubusercontent.com/18227705/29238153-7c45aa5c-7ee3-11e7-8ba5-1df07a23f53c.PNG)

its my project - help me out please .

**Comment by davideast** [comment]
Hi @saqlainIBA! We have a required issue template. There isn't enough information to provide the right answer in this question. However, I recommend using Stackoverflow rather than this repo.

You might want to try changing your firebase import from `import firebase from 'firebase'` to `import * as firebase from 'firebase/app'`. The firebase module has no default export and you want to import only from app to get the typings.
