### ISSUE TITLE
Firebase.d.ts is not a module

### ISSUE THREAD

**Issue by diogokobbi** [angular/angularfire2#1107]
This is a request for documentation update. I've followed the Setup guide but in my case it throws the error "Firebase.d.ts is not a module" on build.

I'm sending a pull request to insert the solution on Troubleshooting.

**Comment by davideast** [comment]
Hey @diogokobbi! Thanks for raising this issue. When do you run into this? I haven't encountered this error since the great TypeScript `2.0` update. I'm not sure it's worth adding to the setup as it's not as common and I'd like to keep things brief. However, I'm still able to be convinced depending on how you ran into it 😀
