### ISSUE TITLE
yarn upgrade downgraded rc.1 to rc0

### ISSUE THREAD

**Issue by markgoho** [angular/angularfire2#1113]
### Version info

**Angular:** 4.3.5

**Firebase:** 4.1.2

**AngularFire:** I thought rc-1

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**
I ran `yarn upgrade`

### Debug output

** Screenshots **
![image](https://user-images.githubusercontent.com/9759954/29417192-5937a72a-8336-11e7-9616-85626acc2c45.png)
### Expected behavior
I would have assumed the package would be upgraded or not upgrade, definitely not downgraded.

### Actual behavior

The package appears to have been downgraded to rc0

**Comment by markgoho** [comment]
Also doing when manually installing rc.2 first
![image](https://user-images.githubusercontent.com/9759954/29436489-c99bef74-8379-11e7-99b2-19ed1d6c58cc.png)

**Comment by larssn** [comment]
So doing `npm install angularfire2@latest --save` will install rc.2 currently, which is fine.

However if you then decide to delete node_modules and simply do an `npm install`, it will downgrade to rc0.

I'm pretty sure it downgrades to `rc0` because the package is named wrong. It should be `rc.0`.

Is it possible to rename the package in npmjs?

**Comment by davideast** [comment]
I don't think will be a problem anymore now that we are on 5.0. Feel free to file another issue if it pops up again.
