### ISSUE TITLE
Update Firebase Version

### ISSUE THREAD

**Issue by esgantivar** [angular/angularfire2#1232]
When update version of angularfire 4.0.0.rc-2 to 5.0.0 some problems appears with compilation of app.
The error description: "Namespace 'firebase' has no exported member 'Promise'."

**Comment by Nebula-Spark** [comment]
@esgantivar 
Check this https://github.com/angular/angularfire2/issues/1199

**Comment by onewiseburdman** [comment]
I think its because of the version you are using I had this problem initially, uninstall using npm and reinstall making sure your version is angularfire2@5.0.0-rc.2.  That fixed my issue with that error.  I am now experiencing some weird issue with importing firebase2 database with a no provider error.
