### ISSUE TITLE
[AFS] Problem when i get nested object

### ISSUE THREAD

**Issue by Anthony2539** [angular/angularfire2#1252]
This is my base:

```Javascript 
  + Spots
        -date
       -message
        - userUid
           + likes 
                   userUid   
```

A collection (spots) witch have attributes date, message, userUid and a collection (likes).
When i retrieve the collection like this:
```Javascript 
getSpotList(batch, lastDate): AngularFirestoreCollection<any>{
      return this.afs.collection('/spots', ref => ref.orderBy('dateUpdate').limit(batch));


this.spotProvider
        .getSpotList(this.batch+1, this.lastDate).snapshotChanges()
        .do(spots => {
   ....
}
```

In my collection spots, i don't have  **likes** collection

**Comment by davideast** [comment]
Hi @Anthony2539! Please use Stackoverflow for these kind of questions. We also have a required issue template to know what exactly you are using.

In your case you will not get back likes since it is a nested collection and those are not automatically retrieved. You will need to manually retrieve them.
