### ISSUE TITLE
Proposal: Compact functions for collection and valueChanges

### ISSUE THREAD

**Issue by hermbit** [angular/angularfire2#1255]
I propose a set of compact functions that would make it much easier to fit Firebase calls on a single line.
These would be convenience functions that would likely be additional to the ones already in place.

First of all, considering that `document` is shortened to `afs.doc`, it would intuitively make sense that `collection` should be shortened to `afs.col`.

Also, adding a `$` after the request type could return the observable, as in `afs.doc$`, `afs.col$`, `afs.list$`, and `afs.object$`. This would return the `valueChanges` observable, since it is used most often.

`afs.col$<Type>('path')` would return `afs.collection<Type>('path').valueChanges();`

**Comment by davideast** [comment]
@hermbit These are good ideas, but there are reasons behind our API.

- We should not rename `collection` to `col` because that would go against the Firestore JS SDK.
- The `$` observable methods are clever but this is a simple to implement utility function on your own. I'm against vanity methods that increase the size of the library. But please feel free to argue with me!

I really appreciate you taking the time to add your ideas. Just because we won't be accepting any of these doesn't mean we won't accept another. We are always interested in feedback from our users.
