### ISSUE TITLE
fix: auth observable should suppress auth state if location.hash contains &__firebase_request_key

### ISSUE THREAD

**Issue by jeffbcross** [angular/angularfire2#131]
When the redirect oauth login flow with a third party provider is complete, the user is redirected back to the app with a hash containing `&__firebase_request_key=<some key>`. The Firebase SDK then asynchronously processes the login success, and will emit a new `AuthState` to AngularFire's callback when it's completed the authentication process. 

Unfortunately, there could be application logic, such as imperative routing logic, that is subscribing to `angularFire.auth` to redirect the user to one route or another based on auth state, and the first value emitted from auth would be `null` since Firebase hasn't yet processed the oauth callback.

AngularFire could help in this situation by looking at the `window.location.hash` as soon as it's loaded, and would optimistically suppress the first `null` `AuthState` from being emitted if such a hash pattern exists.

This assumes that the redirect would never occur, or at least would not include the `__firebase_request_key` hash parameter, if the authentication was unsuccessful.

Thoughts @davideast @katowulf?

**Comment by davideast** [comment]
I'd like to see this in action 👍

**Comment by katowulf** [comment]
I wonder what happens in the case that the redirect back from auth has failed or been canceled by the user? I'm assuming the `null` auth event is the only event triggered in those cases. So it might still need to be triggered? I can't quite remember how all of this works with redirect. I'll ping someone for more details.

**Comment by mikelehen** [comment]
Hrm.  Maybe I'm misunderstanding the issue, but this sounds exactly like something we fixed in the core Firebase JS SDK a year ago ("Fixed an issue where the onAuth event would incorrectly trigger with null while an authWithOAuthRedirect() was in progress." from our 2.2.4 release notes).

Is angularfire somehow re-introducing the problem?  Or am I confused?

**Comment by davideast** [comment]
I've been testing around, and I'm not 100% sure what's going on. But when I authenticate with OAuth or Redirect, I'll get the value form `onAuth` emitted back, but not from the returned promise. Also, Angular seems to not run change detection because none of the templates will update to the newly authenticated state until I refresh. Any ideas @jeffbcross?

**Comment by r-park** [comment]
The templates not updating may be related to angular/angular/issues/8242
