### ISSUE TITLE
AngularFireList.stateChanges() not returning Array of actions

### ISSUE THREAD

**Issue by myspivey** [angular/angularfire2#1373]
### Version info

**Angular:** 5.05

**Firebase:** 4.7.0

**AngularFire:** 5.0.0-rc.5-next

### How to reproduce these conditions

db.list('items').stateChanges().pipe(
      mergeMap(actions => actions),
      map(a => {
        const data = a.payload.val() as T;
        data['$key'] = a.payload.key;
       return data
      })
    );

**Steps to set up and reproduce**

Install latest of Angular, Firebase, AngularFire2. Attempt to access actions array from AngularFireList.stateChanges(). 

### Expected behavior

 Should return Array of AngularFireAction per docs.

### Actual behavior

Instead returns single AngularFireAction.

**Comment by davideast** [comment]
Hey @myspivey! The behavior is correct, the docs are incorrect. The [implementation of the `.stateChanges()` method is really simple](https://github.com/angular/angularfire2/blob/25815cce9c703049ccd6d142703e0e3c6f931cd9/src/database/list/state-changes.ts#L13-L17).

```ts
export function stateChanges(query: DatabaseQuery, events?: ChildEvent[]) {
  events = validateEventsArray(events)!;
  const childEvent$ = events.map(event => fromRef(query, event));
  return Observable.merge(...childEvent$);
}
```

The `.stateChanges()` method creates an observable of each child event provided and merges them into a single observable. Since they are single child events they are fired as a single `AngularFireAction`. 

Note that this is different from the `AngularFirestoreCollection.stateChanges()` method. Firestore returns document changes as an array, even if there's a single change. Therefore [we emit the array of changes](https://github.com/angular/angularfire2/blob/25815cce9c703049ccd6d142703e0e3c6f931cd9/src/firestore/collection/collection.ts#L67-L74) rather than each single change.

```ts
  stateChanges(events?: firebase.firestore.DocumentChangeType[]): Observable<DocumentChangeAction[]> {
    if(!events || events.length === 0) {
      return docChanges(this.query);
    }
    return docChanges(this.query)
      .map(actions => actions.filter(change => events.indexOf(change.type) > -1))
      .filter(changes =>  changes.length > 0);
  }
```

```ts
export function docChanges(query: firebase.firestore.Query): Observable<DocumentChangeAction[]> {
  return fromCollectionRef(query)
    .map(action => 
      action.payload.docChanges // array of changes
        .map(change => ({ type: change.type, payload: change })));
}
```

Now with all that being said, would you like to send a PR in to update the docs? 😃

**Comment by myspivey** [comment]
Will be happy to handle that! Slammed today but will try to get to it tomorrow or Friday. Thanks for the clarification!
