### ISSUE TITLE
error TS2322: Type 'AngularFireList<{}>' is not assignable to type 'Observable<Product[]>'

### ISSUE THREAD

**Issue by famousTM** [angular/angularfire2#1391]
I am running the code below with the latest in all packages, except firebase cause that has issues, so I am using:
"firebase": "4.8.0"

However, I keep getting error:
error TS2322: Type 'AngularFireList<{}>' is not assignable to type 'Observable<Product[]>'

I used this => https://www.youtube.com/watch?v=2ciHixbc4HE example direct from the firebase team. So what is the issue?

`import { Injectable } from '@angular/core';

import {
  AngularFirestore,
  AngularFirestoreCollection,
  AngularFirestoreDocument
} from 'angularfire2/firestore';
import { AngularFireDatabase } from 'angularfire2/database';
import { AngularFireAuth } from 'angularfire2/auth';
import { Observable } from 'rxjs/Observable';

import { Product } from '../models/product';

@Injectable()
export class ProductsService {

  productsCollection: AngularFirestoreCollection<Product[]> = null;
  products: Observable<Product[]>;
  userId: any;
  constructor(public afs: AngularFirestore,
              private db: AngularFireDatabase,
              private afAuth: AngularFireAuth) {
  this.afAuth.authState.subscribe(user => {
  if (user) {this.userId = user.uid; }
  });
  }

  getProductsList(): Observable<Product[]> {
  if (!this.userId) { return; }
  this.products = this.db.list(`products/${this.userId}`);
  return this.products;
  }
  createProducts(product: Product) {
  this.userId = this.userId;
  this.products.push(product);
  }
}`

**Comment by hiepxanh** [comment]
1) this line:` this.products = this.db.list(products/${this.userId});` is that error there ? I need a simple repo or screenshot to have better diagnostic, but you should to change this to become:
` this.products = this.db.list(products/${this.userId}).valueChanges()` to make it become observable.  ` this.db.list(products/${this.userId})` is not a `observable`, it is `AngularFireList<{}>`

2) you should make this request go to stackoverflow, this issue report only when you have BUG or REQUEST, your issue is because you not read the [document](https://github.com/angular/angularfire2/blob/master/docs/rtdb/lists.md)  carefully

**Comment by davideast** [comment]
Hey @famousTM! What @hiepxanh is right. You need to use `.valueChanges()` at the end of `this.db.list(products/${this.userId})`.
