### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by MaciejCaputa** [angular/angularfire2#1441]
I'm interested in your take on semantic versioning. Why are all versions prereleases so far (alpha/beta/release candidate)? That was true for versions 2,4,5. I see that you match the major version of angular (probably no need to keep up with a minor). If no critical bugs on latest RC were reported why not release a stable version e.g. v5.0.0?

**Comment by davideast** [comment]
This library was in alpha, then beta, and now in release candidate. We are trying to provide SSR support and Cloud Messaging support before going to final. We are also working on some performance issues around Zone.js. Since these tasks represent a large chunk of work I'd like to get them landed before going to a final version. However, we do plan on getting there soon.
