### ISSUE TITLE
document snapshotChanges() does not give the type

### ISSUE THREAD

**Issue by Vesuviante** [angular/angularfire2#1512]
**### Version info**
****Angular**: ^5.2.0
****Firebase**: 4.9.1
****AngularFire**:^5.0.0-rc.6

### **How to reproduce these conditions**
on
this.afs.doc(`items/${item}`).snapshotChanges()
when I change a value on doc, o remove it I have always this result in console 
{payload: DocumentSnapshot, type: "value"}

### **Expected behavior**
that type is
 "added" | "modified" | "removed"

### **Actual behavior**
 type: "value" (always)

ciao

**Comment by diginikkari** [comment]
+1 for this. I would really much like to see this implemented.

I'm dispatching ngrx actions based on DocumentChangeAction from collection snapshotChanges and It would be nice to be able to use same logic with individual documents.

**Comment by davideast** [comment]
@diginikkari @diginikkari A Document does not receive added modified or removed events, that is only possible when you listen to a Collection. Otherwise it's just a value changed emission. If you're looking for events for field changes, that is not possible with the SDK. Feel free to file an issue in the official SDK repo.

https://github.com/firebase/firebase-js-sdk/
