### ISSUE TITLE
percentChanges() only emitting the first value 0, and the last 100, no intermediate values

### ISSUE THREAD

**Issue by beautifulboy11** [angular/angularfire2#1763]
### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by davideast** [comment]
Hi @beautifulboy11! I need a lot more information before providing help. Could you provide a brief sample of code? A repo on stackblitz? How large is your file? Some small files can be uploaded in one shot. However, AngularFire is a wrapper around the JS SDK. [File your issue here](https://github.com/firebase/firebase-js-sdk/) if it persists and try to include the information listed above. Thanks!
