### ISSUE TITLE
Firebase is not connecting in Iran IP

### ISSUE THREAD

**Issue by akarai9** [angular/angularfire2#1934]
### Version info

**Angular: 4.1.3

**Firebase: 4.0.0

**AngularFire: 4.0.0-rc.2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by akarai9** [comment]
WebSocket connection to 'wss://s-usc1c-nss-240.firebaseio.com/'  failed: Error in connection establishment: net::ERR_CONNECTION_CLOSED

**Comment by D2KX** [comment]
There are some restrictions to several countries (Crimea, Cuba, Iran, North Korea, Sudan, and Syria) due to sanctions imposed by the US government. This will likely be the case here, and is an issue that GitLab also ran into when they recently moved to Google Cloud.

That being said, your versions are also pretty old, so if you are developing behind a VPN to work around these stupid restrictions and still face problems, it might be worth trying to update your project to a newer AngularFire release.

**Comment by jamesdaniels** [comment]
Far out of scope for this project. [Google is blocking Iran due to sanctions](https://www.treasury.gov/resource-center/sanctions/Programs/Pages/iran.aspx).
