### ISSUE TITLE
Can't import AngularFire from angularfire2

### ISSUE THREAD

**Issue by romeogrey** [angular/angularfire2#1941]
### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by Chan4077** [comment]
If you're using the latest version of AngularFire2, please import from `@angular/fire` instead of `angularfire2`. The NPM package for the original `angularfire2` has been deprecated in favour of the new NPM package `@angular/fire`.

---

P.S. Please consider filling in the issue template or the members of the AngularFire2 team may immediately close your issue without any consideration.
