### ISSUE TITLE
Support region configuration via FunctionsRegionToken is a BREAKING CHANGE

### ISSUE THREAD

**Issue by paulstelzer** [angular/angularfire2#1945]
Today I wondered why my callable functions not working anymore. Then I saw that you tell "Support region configuration via FunctionsRegionToken". But if you not set it, the region is "null" and this region not exists.

So at the moment it is required to add `{ provide: FunctionsRegionToken, useValue: 'us-central1' },` to the providers section. From my point of view everyone who uses AngularFireFunctionsModule and callable functions, this is a BREAKING CHANGE

My feature request
========================

it would be better, if no RegionToken is set, that the default value is 'us-central1'.

**Comment by alberthoekstra** [comment]
Sweet, this saved me some time.
I'm developing a Ionic3 app and was trying the new Functions module. Without the above solution the url started with 'https://null-' because the region info is missing.

This is also not documented [here](https://github.com/angular/angularfire2/blob/master/docs/functions/functions.md)
