### ISSUE TITLE
ERROR Error: “[object Object]”.  When page is reloaded

### ISSUE THREAD

**Issue by dazzHere** [angular/angularfire2#2070]
This error appears when db.object() is referenced with `auth.currentUser.uid`

**Comment by hooloom** [comment]
It would be best for you to console log the error, right now it appears you have not captured the error - that's why you are seeing object Object.  It's some sort of observable event - but beyond that, one would never know what it is.  

In case you don't know how to do error handling.  https://blog.angularindepth.com/expecting-the-unexpected-best-practices-for-error-handling-in-angular-21c3662ef9e4

**Comment by dazzHere** [comment]
Ok thanks, i'll check it out.
