### ISSUE TITLE
Steps To Build Project

### ISSUE THREAD

**Issue by Chuckv01** [angular/angularfire2#277]
One of the recent fixes (#243) has not been pushed to npm yet. I've cloned the git repository and attempted to build the dist package myself using "npm run build", but I'm getting this error:

"error TS6053: File 'typings/main.d.ts' not found."

The build seemed to complete successfully, but when I load the contents of the dist directory into my project I get the error:

" Error TS2307: Cannot find module 'angularfire2'."

Makes me think I did not build the project correctly? What are the steps to build? It would be nice to have those in the docs.

**Comment by jeffbcross** [comment]
We'll probably cut a release today or tomorrow that includes the fix to #243. In the meantime, you can install it using the `@next` tag: `npm install angularfire2@next`. 

Regarding your 2nd suggestion: yes, our contributor docs should be up-to-date to tell how to build the project. In your case, you're just missing the step of installing typings (which isn't documented). You can run: `./node_modules/.bin/typings install` from the root of the project, and your problems should go away. I'd removed a `postinstall` script that automatically installs typings so that end-users wouldn't add that time to their install process, but it would be better for me to add the `postinstall` script back and just strip it out of the package that gets pushed to npm.

TODO
 - [ ] Add postinstall script to package.json to automatically run `typings install`
 - [ ] Add step to `tools/rewrite-published-package.js` to strip `scripts` from the package.json that gets published to npm.
