### ISSUE TITLE
DataSnapshot example in /docs/3-retrieving-data-as-lists.md doesn't work

### ISSUE THREAD

**Issue by cweidinger** [angular/angularfire2#327]
When I used the instructions at https://github.com/angular/angularfire2/blob/master/docs/3-retrieving-data-as-lists.md to get a snapshot of a list using the exact code on that tutorial

```ts
this.items = af.database.list('/items', { preserveSnapshot: true });
this.items
  .do(snapshots => {
    snapshots.forEach(snapshot => console.log(snapshot.key()));
  })
  .subscribe(snapshots => console.log(snapshots.length));
```

I get the following error

`Property 'do' does not exist on type 'FirebaseListObservable<any>'`

I followed the example using the 'ng' cli to setup everything.

On a similar note when I tried to "Retrieve the Snapshot" using the following code from the bottom of https://github.com/angular/angularfire2/blob/master/docs/2-retrieving-data-as-objects.md

```ts
this.item = af.database.object('/item', { preserveSnapshot: true });
this.item.subscribe(snapshot => console.log(snapshot.key()));
```

I got the following error
`snapshot.key is not a function`

In this case it was a property but when I tried to find snapshot.value() I got the same error but the value was not even a property.

Thanks for looking into this

**Comment by lf-alves** [comment]
Kind of dumb of me to ask, but did you try snapshot.value() or snapshot.val()? 

The Firebase API is DataSnapshot.val() not .value();

I'm using that same syntax, also preserving the snapshot, and it works just fine.

Firebase just went through a major update like 2 months ago and snapshot.key() turned into snapshot.key and the angularfire docs weren't updated, that's why you got that error.

**Comment by cweidinger** [comment]
You're right @lf-alves. it's snapshot.val(). I've made a PR for the docs #334

**Comment by davideast** [comment]
Thanks for the issue then the PR!
