### ISSUE TITLE
Firebase folder is not being created in dist/vendor

### ISSUE THREAD

**Issue by sitrucj** [angular/angularfire2#364]
As far as I can tell I have followed the steps in the developer guide and I have an angularfire2 folder in vendor now but no firebase folder. I used the cli to make the project and used the steps in dev guide part one with no success. 

As an aside the /vendor/angular2 is giving 404 errors even though it does exist. I can post any files on request but I am not sure where to start. Thanks for any and all help!

**Comment by lf-alves** [comment]
Something similar happened to me once, but it was because I had ran ng serve before ng build after modifying system-config.ts, so the folders weren't created.  Anyway, I'd suggest you to post here the important parts of your system-config.ts file (const map and const packages) and the code inside angular-cli-build.js.

**Comment by sitrucj** [comment]
Ty. Will do

**Comment by sitrucj** [comment]
(100th) ng build did it.. I must have messed something up.. then fixed it recently... THANK YOU!
