### ISSUE TITLE
reset password functionality not available

### ISSUE THREAD

**Issue by sathishvj** [angular/angularfire2#374]
This has been raised twice before, #220 and #247, but it looks like both are closed without it actually being fixed.  Can we leave this open until it is fixed so that it is trackable?

**Comment by davideast** [comment]
There are many auth methods we need to implement, and I don't think it makes sense to have each one as an issue. We plan on creating a larger issue in the future when we are ready to tackle large auth support.

In the meantime it's perfectly fine to use `firebase.auth().sendPasswordResetEmail(emailAddress)` from the regular SDK.

**Comment by bjornson** [comment]
@davideast Is the pure firebase sdk included in angularfire2 and how can I access it within an angular2 .ts file? Im am only getting offered "AngularFire, FirebaseAuth, FirebaseAuthState" and the observables. Thanks!

**Comment by katowulf** [comment]
import * as firebase from 'firebase'; should get you access. It's a bit
temperamental if you upgraded from alpha, so check some of the existing
issues if you get an error.

On Nov 18, 2016 3:02 AM, "bjornson" <notifications@github.com> wrote:

@davideast <https://github.com/davideast> Is the pure firebase sdk included
in angularfire2 and how can I access it within an angular2 .ts file? Im am
only getting offered "AngularFire, FirebaseAuth, FirebaseAuthState" and the
observables. Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/angular/angularfire2/issues/374#issuecomment-261505903>,
or mute the thread

**Comment by bjornson** [comment]
@katowulf thanks for the info, I ended up injecting FirebaseApp in the contructor:

```
private _firebaseApp;
constructor(@Inject(FirebaseApp) firebaseApp: any){
    // listen to auth state change
    this._firebaseApp.auth().onAuthStateChanged(user => {
        if (user) {
            // is logged in
        } else {
            // is logged out
        }
    });
}

requestPasswordResetEmail(email){
    this._firebaseApp.auth().sendPasswordResetEmail(email)
                .then(response => resolve(response),
                    err => reject(err));
}
```

A great side effect is that the auth listener in my app now works on iOS Safari browser as well. So far the only modern browser that had any trouble with the AngularFire auth listener.

**Comment by mubasshir** [comment]
is completed now?

**Comment by raugaral** [comment]
Where is the function to send a code to reset the password?? 
I can see that "confirmPasswordReset(code, newPassword)" but without a function to send the reset code, don't make sense ....
