### ISSUE TITLE
query list with async

### ISSUE THREAD

**Issue by matt-erhart** [angular/angularfire2#407]
What are the current requirements to bind a queried list with async and still be able to push/remove on the queried list? Which newest versions of angular, firebase, and angularfire are known to work? If it doesn't currently work as it did here https://github.com/davideast/firebase-angular2-demo
```
*ngFor="let message of messages | async"
 this.messages = this.af.database.list('/messages', {query: { limitToLast: this.limitSubject  }})
this.messages.push({text: some_text)
```
How does it work now? Would be great to have a simple and current chat-app repo/seed project, so it's easy to jump in and explore a current example.

**Comment by aguzubiaga** [comment]
I don't know if you can push to queried list. But what you can do is something like:

```ts
this.af.database.list('/messages').push({ text: someText });
```
You can even keep the reference to that non queried list in a variable because Observable are lazy so if you don't subscribe to them, they don't emit values. Anyway, firebase caches everything and syncs when it's changed 😉

**Comment by davideast** [comment]
@matt-erhart This is a bug we have fixed in master, so hang tight! Working on a big release atm.
