### ISSUE TITLE
updating af2 and getting typing error

### ISSUE THREAD

**Issue by shamrozwarraich** [angular/angularfire2#431]
in ionic 2 project everything working fine but when updating the angularfire2 getting typing error :/
`npm install firebase angularfire2@next --save`

![errr](https://cloud.githubusercontent.com/assets/13496744/17642489/bb8df110-60fd-11e6-9f4c-15647ec69374.PNG)

**Comment by tomasvio** [comment]
don't forget
`$ typings install file:node_modules/angularfire2/firebase3.d.ts --save --global && typings install`
[Angularfire2/Installation and Setup](https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md#3-include-firebase-sdk-typings)

**Comment by davideast** [comment]
@shamrozwarraich @tomasvio 

Actually, the`firebase3.d.ts` are the problem. The latest Firebase SDK ships with typings, which we have switched to in the pre-release.

If you're using the pre-release (`@next`) version, remove the `firebase3.d.ts` from either your `tsconfig.json` or `typings.json` file.

**Comment by yashmurty** [comment]
@davideast, I've been trying to get AngularFire2 to work since yesterday by following the steps mentioned. But I'm just not able to finish STEP 1 : Installation and Setup. Something or the other keeps breaking. 

Step 1 : 
Used `ng new angular-af2` to create a new project using the Angular CLI webpack version **angular-cli: 1.0.0-beta.11-webpack.2** ( I had to use RC5 because RC4 didn't have BrowserModule in angular core if I remember correctly)
It works fine and I'm able to do `ng serve`

Step 2 : 
`npm install firebase angularfire2 --save` fails due to unmet peer dependency. 
So I run `npm install firebase angularfire2@next --save`. This solves all the angular dependency issues but leaves me with Typescript issue. 

![screenshot from 2016-08-13 22 51 46](https://cloud.githubusercontent.com/assets/1630458/17644612/ef808590-61a8-11e6-8c3d-d6cbc227f36d.png)

Manually changing it in the `package.json` doesn't yield any good results. Here is the screenshot of what happens by changing it to 1.8.0 or 1.9.0-dev.
![screenshot from 2016-08-13 22 57 55](https://cloud.githubusercontent.com/assets/1630458/17644635/7d14f65c-61a9-11e6-9079-94b76ca21ea0.png)

Step 3 :
If I were to ignore these errors and move on to 
`typings install file:node_modules/angularfire2/firebase3.d.ts --save --global && typings install`
This also fails since there is no firebase3.d.ts file present. ( And as you mentioned above, we don't need this file anymore.)

So skipping all the steps, if I directly add
`import { AngularFireModule } from 'angularfire2';` in my app.module.ts and do `ng serve` I get the following series of errors. 
**ERROR in [default] /var/www/webops/angular-af2/node_modules/angularfire2/angularfire2.d.ts:13:65 
Cannot find namespace 'firebase'.**

So finally what should I do to get my setup running with RC5? 
Your help will be appreciated! :)

**Comment by danielgek** [comment]
@yashmurty see #425

**Comment by davideast** [comment]
@danielgek Interesting that works for non 2.0 projects, I'll check that out!

@yashmurty Try install TypeScript 2.0+ either:

```bash
npm install -g typescript@2.0
#or
npm install -g typscript@next
```

**Comment by yashmurty** [comment]
@danielgek Thank you very much. It fixed my problem **Cannot find namespace 'firebase'.**

@davideast I successfully executed the typescript 2.0 installation. I no longer receive the **UNMET PEER DEPENDENCY** issue. I just get some warnings on running `npm install` from project root. 
`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:`
`npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14`
`npm WARN @angular/tsc-wrapped@0.2.2 requires a peer of typescript@^1.9.0-dev but none was installed.`
`npm WARN tsickle@0.1.6 requires a peer of typescript@^1.8.0 || ^1.9.0-dev but none was installed.`
But I think I can ignore that? Also, even with the **Cannot find namespace 'firebase'.** issue, I was still able to run the **AngularFire** functions from **angularfire2** as given in the examples. Which is surprising because I thought it depended on Firebase and would break.

**Comment by davideast** [comment]
@yashmurty Those `npm WARN` warnings are because you are on a windows machine, but unless you're running karma in the AF2 project itself you won't run into any issues. There's also a workaround, but that's not necessary now.

The namespace issue *should* have been because you were on <2.0. Are you still getting it with the following import?

```js
import * as firebase from 'firebase';
```

**Comment by shamrozwarraich** [comment]
what change occur in new af ? not show in changelog ... :/

**Comment by davideast** [comment]
We don't create changelogs for pre-releases. Once we get enough feedback on it we will release to main and create a changelog.

**Comment by RedFour** [comment]
@danielgek and @yashmurty, could you explain what exactly you did that got rid of the "Cannot find namespace 'firebase'" issue? I've read and tried all the suggestions in this and the other thread, and still getting the issue.

**Comment by yashmurty** [comment]
@RedFour, I read you comments on the thread [#425](https://github.com/angular/angularfire2/issues/425). Apparently it's a Windows OS problem? 

Apart from the solution of adding `firebase` to the types array of `tsconfig.json`, you could try importing Firebase in your **app.module.ts** file by typing this.
`import * as firebase from 'firebase';`

**Comment by RedFour** [comment]
Thanks, this got rid of the errors for me!

**Comment by robbatt** [comment]
@yashmurty Same problem on win10, this solved it, Thanks! You should add this to the docs!
