### ISSUE TITLE
Firebase query & sorting technique for pagination

### ISSUE THREAD

**Issue by beckmeindia** [angular/angularfire2#477]
Hey, I am trying to build a travel app where users can filter the items based to departure and arrival locations.
I am trying to use firebase query/sorting with pagination. Is there a way to show only 20 items (like first 20 and then paginate for every 20 items) rather than loading all the data against a certain firebaseurl with observables.

Thanks

**Comment by davideast** [comment]
@beckmeindia 

Hello! I'm going to close your question because it is best suited for another medium like the Firebase Google Group or the Firebase Slack Community. This repo is focused on troubleshooting library centric issues. Thanks for reaching out through, and I can assure you that those mediums are active and will be able to help.

https://firebase-community.appspot.com
https://groups.google.com/forum/#!forum/firebase-talk

Cheers,
David

**Comment by beckmeindia** [comment]
Sure thanks. Will post there
