### ISSUE TITLE
perf(FirebaseListFactory): new array emitted for each item initially loaded

### ISSUE THREAD

**Issue by jeffbcross** [angular/angularfire2#52]
Since the synchronized array is typically populated using the `child_added` event for a list instead of `value`, a new array is being emitted from the observable for each initial child in the list. 

For perf and general ergonomic reasons, we should explore emitting the array of initial values once.

**Comment by davideast** [comment]
This can be down by using a `.once()` call to get the initial set of data, and then subscribing to `child_added` events.

```ts
let arr = [];
const ref = new Firebase("");
ref.once("value", (data) => {
  data.forEach((item) => arr.push(item));
  ref.orderByKey().startAt(arr[arr.length -1].key()).on("child_added", (snap) => arr.push(snap));
});
```

**Comment by jeffbcross** [comment]
Hello? Update plz?

**Comment by davideast** [comment]
Okay, after further thought and review, here is my proposal:

**[JSBin Demo](http://jsbin.com/bironiqibo/1/edit?js,console)**

```js
const ref = new Firebase('https://<my-firebase-app>/messages');

// helper function for placing the key on the object
const itemify = (snap) => {
  let value = snap.val();
  let item = {};
  if (typeof value !== 'object') {
    item.value = value;
  } else {
    item = snap.val();
  }
  item._key = snap.key();
  return item;
};

ref.once('value')
   // get the initial array one-time with once()
   .then((snap) => {
      let initialArray = [];
      snap.forEach((child) => {
        initialArray.push(itemify(child));
      });
      return initialArray;
   })
   .then((initialArray) => {
     let initialLoad = false;
     // get the last key in the initialArray
     const lastKey = initialArray[initialArray.length - 1]._key;
     
     // listen for children
     // This is not data wasteful because the initial load fires
     // from the cache, not from the network
     ref.on('child_added', (child, prevKey) => {
     
       // ignore children from the initial load
       // was the previous child, the last item in the initial load?
       if(prevKey === lastKey) {
         initialLoad = true;
         // loaded here
         console.log(initialArray);
       }
          
       // If the initial load has completed, then add to the array
       if (initialLoad === true) {
         initialArray.push(itemify(child));
         console.log(initialArray);
       }
       
     });

     ref.on('child_removed', (child) => {

     });

     ref.on('child_changed', (child, prevKey) => {

     });

        
   });
```

**Comment by jeffbcross** [comment]
It seems like a reasonable approach to me.

Regarding the actual implementation, I would want to use Observable instead of promise, so that it will play nicely with the work I'm doing on interactive querying. Mostly, I want to make sure I can cancel the completion of the promise chain if the query has changed.

```typescript
PromiseObservable.create(ref.once('value'))
  .map(items => items.map(itemify)
  .flatMap((initialArray) => {
    return new FirebaseObservable(observer => {
      let initialLoad = false;
      const lastKey = initialArray[initialArray.length - 1]._key;
      ref.on('child_added', (child, prevKey) => {
        if(!initialLoaded && prevKey === lastKey) {
          initialLoad = true;
          // loaded here
          console.log(initialArray);
        }

        // If the initial load has completed, then add to the array
        if (initialLoad === true) {
          initialArray.push(itemify(child));
          console.log(initialArray);
        }
      });
      
      // Add other listeners
      ...
      
      return () => ref.off();
    });
  });
```

**Comment by katowulf** [comment]
This might be simpler if add values _before_ "initial load" are treated the same as one after "initial load". To state this inversely, there is probably no reason for those two states to behave differently, and then there would be exactly one way to populate values into the array.

You can simply call the on('child-added'...) and have it push things to the array, and call once('value',...) _after_ this. Now when once('value',...) is triggered, you know the "initial" data is all present (see [event guarantees](https://www.firebase.com/docs/web/guide/retrieving-data.html#section-event-guarantees)). At this point, you can trigger whatever code will cause the change detection to occur (such as fulfilling the promise perhaps?).

Even slightly more elegant, in my opinion, is abandoning the idea of initial load. It really is no different than any other time during the operation of the page (it's just a big influx of added events), so treat it the same and use a debounce to trigger the change detection event, so that UI renders are batched nicely.

I'd be a little more explicit, but I can't tell in the above how change detection is triggered or what effect pushing things into the array might be having behind the scenes.

**Comment by jeffbcross** [comment]
@katowulf thanks for the idea. I think this would be the best strategy, and we could utilize observable operators to accomplish it pretty easily. We just have to think about the right strategy. I think we should implement #55 before implementing this, since it would make it easier.

@davideast I'll go ahead and unassign this unless you've started work on it.

**Comment by davideast** [comment]
@jeffbcross I'm working on this and #73 since they are related.
