### ISSUE TITLE
AngularFire2 worked even though I've forgotten to add it in vendor.ts

### ISSUE THREAD

**Issue by bogacg** [angular/angularfire2#521]
Hi;
I'm using webpack and AngularFire2 in my project.
Even though I've forgotten to add import statement for angularfire2 and firebase in vendor.ts, my app worked.
Shouldn't app be broken unless we add it to?

**Comment by asadsahi** [comment]
I wonder this as well, I suspect, its because of new module system in angular 2. Not sure, lets hear experts :).

**Comment by jeffbcross** [comment]
Hey @bogacg I don't know enough about your project to know what's happening. I'll close this issue, but if you want to open a new issue with a github repo or something where we could inspect more, feel free!

**Comment by asadsahi** [comment]
@jeffbcross [this](https://github.com/asadsahi/ng2fb-bootstrap) repo should illustrate this query I hope, its a cli based project.

If you see this [line](https://github.com/asadsahi/ng2fb-bootstrap/blob/master/src/app/app.module.ts#L5) we are only importing angularfire2 module using typescript/es6 syntax, but in past we have to use **import 'angularfire2'** in vendor files first. 

I think this beavior of not importing 3rd party libraries in vendor files anymore and only importing like es6 syntax applies to all other 3rd party libraries.

Correct me if I am wrong, is this because of webpack 2's ability to handle es6 natively that we don't have to import AMD or commonjs like imports anymore?

**Comment by bogacg** [comment]
@jeffbcross I've seen this problem right after I've added AngularFire2 to a newly created project from: [WEBPACK: AN INTRODUCTION](https://angular.io/docs/ts/latest/guide/webpack.html) 
Sure, it may not be an anomaly related to "your" work or AngularFire2, I'd be happy then pass along to Angular 2 project's issues section or Webpack.

**Comment by asadsahi** [comment]
@bogacg the problem/query mentioned in the title of this issue isn't specific to angularfire2, if you add any other third party library like ng-bootstrap in an angular 2 project and directly start using them in your angular modules or other files, without adding that library in vendor.ts file, you will not see any error.

I think its because of the new way webpack 2 handles dependencies, not sure, hence raised to @jeffbcross  if he can share his experties in this area.
