### ISSUE TITLE
Working with multiple observables: Any examples?

### ISSUE THREAD

**Issue by theunreal** [angular/angularfire2#634]
Since Angualrfire2 requires working with multiple observables and different data from Firebase.
it could be great if there were any example of Angularfire2 usage receiving data from different nodes.

I've been working on an application and created flat database structure as the guidelines, and this is what I ended up with:

```
ngOnInit() {
    //Subscription 1 (Service): Get project data
    this.projectService.getCurrentproject().take(1).subscribe(projectData => {
        console.log('Got project data.');
        //Subscription 2: Get project user IDS
        this.af.database.list('/project_roles/'+projectData.$key)
            .subscribe((userMeta) => {
                console.log('Got User IDS.');
                //Loop: For each user ID/Role ID, get the data
                userMeta.forEach((projectRole) => {
                    console.log("Got user meta");
                    //Subscription 3: role ID to role Name
                    this.af.database.object('/roles/'+projectRole.$value)
                        .subscribe((roleData) => {
                            console.log("Got user role name");
                            //Subscription 4: Get user info
                            this.af.database.object('/users/'+projectRole.$key).subscribe(user => {
                                console.log("Got user info");
                                user.role = roleData.$value;
                                this.users.push(user);
                            });
                        });
                });
            });
    });
}
```

Database example:

```

users : {
 user1 : {
  name : blah,
  email : a@a.com,
    }
  },

projects : {
  projectKey1 : {
    name : blahserve,
    category : blahbers,
    }
},

projectsLists:{

  user1 :{
    projectKey1 : true,
    projectKey2 : true 
    }
}, 

projectsRoles :{

  projectKey1 : {
     user1 : provider,
     user2 : editor,
     ....
    }
  }

```

I ended up with 4 subscriptions, and 2 others from the service. I need to make `1 + (numUsers*2)` calls to firebase in order to fetch my user list.
1. Call to projectsRoles/$projectID to get all user IDS of the current project.
2. Loop each USER ID+Role ID received: 
3. Get the role name by roles/$roleID
4. get user information by users/$userID

Is it common to make so much calls to receive data from firebase?

**Comment by sean-hill** [comment]
Hey @theunreal what was your solution here?

**Comment by theunreal** [comment]
No solution so far, I might have changed the db structure a bit

**Comment by clark-stevenson** [comment]
This one is killing me.  

I need to go to `groups/x/members` where I am going to find some keys for members of that group.

What I really need though, is not the keys, but the actual Observables for those keys.  I need to return somekind of "FirebaseListObservable` and do what FirebaseListObservable does..... but, I need to build it myself.

I don't know how to go from `groups/x/members` keys into essentially a bindable async list and return it to be useful. 

```
`users/userKey93489329482/`
`users/userKey39843904829/`
```

I burned days on it, My best result so far is to get the members keys, do a `switchMap` use the keys to create an array of Observables, and then combine those Observables together with `combineLatest` but this doesn't work for Angular2 for some reason.  I think it is because if members is now empty, `combineLatest` makes no sense and it is like Angular doesn't get informed (But the console log does!!). 

I pretty much don't know where else to go with this.

**Comment by sebastiandenisdotcom** [comment]
I've found something that can be helpful:
[(http://www.clearlyinnovative.com/sample-firebase-angularfire2-with-angular-cli-application)]
