### ISSUE TITLE
Cannot find namespace "firebase" Followed the steps in troubleshooting.

### ISSUE THREAD

**Issue by oberoivarun** [angular/angularfire2#638]
```
ng new app
cd app

npm install -g typings
npm install -g typescript

npm install firebase angularfire2 --save
```
Then added the following to app.module.ts
```
export const firebaseconfig = { ... };

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    AngularFireModule.initializeApp(firebaseConfig)
  ],
  providers: [],
  bootstrap: [AppComponent]
})
```

and ```ng serve```

Giving me error "Cannot find namespace firebase"

I added 
```
"types": [
      "firebase"
    ]
```
as recommended in installation guide and also added
```
declare var require: any;
declare var module: any;
```
in main.ts

Getting error: and tried many scattered fixes found throughout the internet:

```
Cannot find namespace "firebase"
```

tried this:

```
In main.ts i added this line
import * as firebase from 'firebase';
```

New error:
```
ERROR in [default]
Cannot find type definition file for 'firebase'.
```

So i did ```typings install --save dt~firebase```
Then also tried ```typings i```
No effect. Tried a couple of other tricks, nothing has helped yet.

Please help!

**Comment by Irocode** [comment]
i have the some problem

**Comment by mukesh51** [comment]
@oberoivarun @Irocode Everything should work as expected. After seeing your issue, I just followed the steps again from [Install guide](https://github.com/angular/angularfire2/blob/master/docs/1-install-and-setup.md) to see, if anything seems broken. It's working fine for me on Windows 10 machine. See the below ng and node version for your reference.

In fact you don't need to do any of the steps mentioned in the troubleshooting section. The console might throw errors on WIndows machine, but the connectivity still works with FIrebase. these errors are not thrown on linux/mac os.

`C:\afTestApp>ng -v`
angular-cli: 1.0.0-beta.15
node: 6.5.0
os: win32 x64

`C:\afTestApp>node -v`
v6.5.0

**Comment by davideast** [comment]
@oberoivarun 🤔  Writing `import * as firebase from 'firebase'` should have fixed the trick.

Do not use the definitions from typings, as the definitions you need are in the firebase node module.

I'm unfortunately going to have to close this issue because it has not followed the issue template. This may seem tedious, but your issue leaves out what versions of everything you are using. AngularFire2 is a library the depends on Angular2, Firebase, and RxJS so know what version is really important. Not knowing versions, and whether you're on the Angular CLI makes it really hard for us to help solve your problem. Please open an other issue with all of the needed info and we can help you out 😀

**Comment by mpeguero** [comment]
Maybe they have make the same mistake as me. Everything was working properly, but after I made 
some changes on my directory structure the compilation started showing this error:
Cannot find type definition file for 'firebase';

**Comment by mpeguero** [comment]
davideast : Do we really need angularfire2 to interact with Firebase? So they firebase API have all method 
necessary to access data and save data into firebase. Why add a new layer?
