### ISSUE TITLE
How To Setup Firebase Cloud Messaging 

### ISSUE THREAD

**Issue by mohsinAjency** [angular/angularfire2#660]
### Version info

**Angular:** 2

**Firebase:** 3

**AngularFire:** 2

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** ionic 2

I want to setup push notification using FCM for my IONIC 2 app. How should i go about it and is there any tutorials or blogs you can point me to. And does angularfire2 support fcm methods ??

**Comment by katowulf** [comment]
This isn't the right forum for FCM and you haven't followed the issue template. We can answer specific technical issues about AngularFire2, and some questions about Angular and Firebase, but only if you've done the due diligence required in the issue template.

FCM guide is [here](https://firebase.google.com/docs/cloud-messaging/). You don't need AngularFire2 to implement this.

**Comment by jeremiahgibson91** [comment]
Katowulf no disrespect but your wrong. I don't want to have to include firebase twice, to use fcm it should be included in angularfire2 module. But the messaging functionality is missing. You should be able to access .messaging portion of the angularfiremodule object but it's completely missing. Currently I have to import firebase and angularfire2module in order to get both the database observables and FCM
