### ISSUE TITLE
is there a watch feature similar to angularfire-1 ?

### ISSUE THREAD

**Issue by ituhin** [angular/angularfire2#703]
how to get notified when a firebase object/list (which i am listening to) gets modified ?
looking for something similar to $watch() in angularfire-1

Thanks 👍

**Comment by katowulf** [comment]
Since objects/collections are [Observables](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/observable.md), you just use [Observable.prototype.subscribe()](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/subscribe.md).

All issues have to follow the issue template provided. This is critical to keep things streamlined and manageable. Closing this. Feel free to resubmit according to the template; if you do, be sure to include a working, minimal repro of the problem and version info.

**Comment by ituhin** [comment]
@katowulf thanks 👍 

and what is the equivalent of $loaded feature ?

**Comment by katowulf** [comment]
.first().subscribe().
