### ISSUE TITLE
Need a very clear example of how to use password auth. Only fragments in documentation. No examples seem to work.

### ISSUE THREAD

**Issue by Energy4216** [angular/angularfire2#720]
### Version info

**Angular:**

**Firebase:**

**AngularFire:**

**Other (e.g. Ionic/Cordova, Node, browser, operating system):**

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **

** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by katowulf** [comment]
All issues have to follow the issue template provided. I understand this is asking a lot and is generally annoying when you feel your question is straightforward, but just trust that it's critical to keep things streamlined and manageable for our team. I'm closing this for now because it doesn't adhere to these requirements. Feel free to resubmit according to the template, being absolutely sure to include a working, minimal repro of the problem and version info. 

Note that how-to questions are better suited for Stack Overflow or a discussion group. In your case, since you've mentioned it "doesn't seem to work" you should be submitting a failing repro that follows one of the samples.

**Comment by Energy4216** [comment]
Hi. does the password authentication work with rc6? Just curious. I'm a nooby thank you for your time.


________________________________

**Comment by katowulf** [comment]
It should work with other RCs, but as with any beta release, you'll always want to stay ahead of the bugs and on the latest version.
