### ISSUE TITLE
I used a starter from https://github.com/antonybudianto/angular2-starter  no luck when adding angularfire2

### ISSUE THREAD

**Issue by foxjazz** [angular/angularfire2#723]
<!--

IMPORTANT! YOU MUST FOLLOW THESE INSTRUCTIONS OR YOUR ISSUE WILL BE CLOSED.

use this starter
https://github.com/antonybudianto/angular2-starter

just add the module and sug to the todolist (it doesn' thave to do anything) and errors on runtime.

my attempt ad adding a memberlist is here:
[https://github.com/foxjazz/memberbase.git](https://github.com/foxjazz/memberbase.git)

**Comment by katowulf** [comment]
All issues have to follow the issue template provided. I understand this is asking a lot and is generally annoying when you feel your question is straightforward, but just trust that it's critical to keep things streamlined and manageable for our team. I'm closing this for now because it doesn't adhere to these requirements. Feel free to resubmit according to the template, being absolutely sure to include a working, minimal repro of the problem and version info. 

Note that how-to questions are better suited for Stack Overflow or a discussion group.
