### ISSUE TITLE
Using firebase list as image src - refreshing problem

### ISSUE THREAD

**Issue by Metafili** [angular/angularfire2#727]
hi,

i m retrieving thumbnail urls from firebase db and displaying images on timeline.
this causes trouble on safari and on ios device: 
when i add new note, app is request the thumbnails from the firebase again. 

view:  <md-card *ngFor="let note of notes | async" >
            <span *ngIf="note.thumbnail" >{{note.thumbnail}}></span>
            <md-card-content>{{note.title}}</md-card-content>
        </md-card>

controller: 
    this.notePath = `/users/${auth.id}/notes/`;
    this.notes$ = af.database.list(this.notePath);

 
here s the timeline.
![image](https://cloud.githubusercontent.com/assets/9953374/21399425/3ab52482-c7b4-11e6-898b-83242a58d073.png)

thank you for helping me

**Comment by katowulf** [comment]
All issues have to follow the issue template provided. I understand this is asking a lot and is generally annoying when you feel your question is straightforward, but just trust that it's critical to keep things streamlined and manageable for our team. I'm closing this for now because it doesn't adhere to these requirements. Feel free to resubmit according to the template, being absolutely sure to include a **working, minimal repro of the problem and version info**. 

Note that how-to questions are better suited for Stack Overflow or a discussion group.
