### ISSUE TITLE
RXJS 5.0.1

### ISSUE THREAD

**Issue by boskiv** [angular/angularfire2#730]
Should it changed in package.json ?

**Comment by Blankarsch** [comment]
RXJS 5.0.1 doesn't work for me...

**Comment by davideast** [comment]
@Blankarsch What is your problem? I just updated the lib, all the tests pass and everything seems to be working just fine.

**Comment by paramburu** [comment]
Hi, having issues since angular and ionic are using rxjs@5.0.0-beta.12 but angularfire is using ^5.0.1... can't shrinkwrap either way.

`npm ERR! peer dep missing: rxjs@5.0.0-beta.12, required by @angular/core@2.2.1
npm ERR! peer dep missing: rxjs@5.0.0-beta.12, required by @angular/http@2.2.1
npm ERR! peer dep missing: rxjs@5.0.0-beta.12, required by ionic-angular@2.0.0
npm ERR! peer dep missing: rxjs@5.0.0-beta.12, required by @angular/core@2.2.1`

Any suggestions? Thanks
