### ISSUE TITLE
Query: Multiple database support.

### ISSUE THREAD

**Issue by sudharsanmit** [angular/angularfire2#761]
Does Angularfire2 support multiple firebase projects? If so, how to implement it? I read about it in the below googleblog.

> https://firebase.googleblog.com/2016/12/working-with-multiple-firebase-projects-in-an-android-app.html

**Comment by davideast** [comment]
@sudharsanmit You can create a new app and pass in the reference.

```ts
const app = firebase.initializeApp({ ... });
const ref = app.database.ref('items');
const listObs = af.database.list(ref);
```

**Comment by sudharsanmit** [comment]
@davideast Thanks for your response. This doesn't seem to work. I am not able to reference database on app, i.e. app.database is erring out!

```
import {Injectable,Inject} from '@angular/core';
import { AngularFireModule,AngularFire, AngularFireAuth, AngularFireDatabase } from 'angularfire2';

@Injectable()
export class secondaryDB {
	secondary:any;
	constructor (private af:AngularFire){

	}

    init(config){
        const app = AngularFireModule.initializeApp(config);
        const ref = **app.database.**items('items');
        const listObs = this.af.database.list(ref);
    }

```

**Comment by sudharsanmit** [comment]
![image](https://cloud.githubusercontent.com/assets/16746593/21865739/93a1cba8-d804-11e6-9642-e65acf506b57.png)

I am not able to get it to work. Method ref is not existing on app.database.

**Comment by katowulf** [comment]
Try `app.database().ref()` instead.

**Comment by sudharsanmit** [comment]
Thanks @katowulf . I got it working!

```
    init(config){
        const app = firebase.initializeApp(config,"secondary");
        const ref = app.database().ref('/test');
        const listObs = this.af.database.object(ref);
        listObs.subscribe(data => console.log(data));
    }

```

**Comment by chetanbnaik** [comment]
Please share a detailed code on how to implement the multiple database through angularfire

**Comment by daimz** [comment]
@sudharsanmit Are you able to please share a more detailed example of how you got this working, I am currently trying to do the same but unclear on how to set it up correctly.

**Comment by sudharsanmit** [comment]
@daimz @chetanbnaik 

Service : 

```
import {Injectable,Inject} from '@angular/core';
import { AngularFireModule,AngularFire, AngularFireAuth, AngularFireDatabase } from 'angularfire2';


@Injectable()
export class secondaryDB {
	secondary:any;
	constructor (private af:AngularFire){

	}

    init(config){
        const app = firebase.initializeApp(config,"secondary");
        const ref = app.database().ref('/test');
        const listObs = this.af.database.object(ref);
        listObs.subscribe(data => console.log(data));
    }

    setSecondary(secondary){
    	this.secondary = secondary;
    }

    getSecondary(){
    	return this.secondary;
    }
}
```

Controller:

```
@Component({
  templateUrl: 'test.html'
})
export class TestPage {
  constructor(private secDB:secondaryDB) {

  var config = {
    apiKey: "XXXXXX",
    authDomain: "XXXX.firebaseapp.com",
    databaseURL: "https://XXXX.firebaseio.com",
    storageBucket: "project-XXXX.appspot.com",
    messagingSenderId: "XXXX"
   };    
    secDB.init(config);
  }
}
```

**Comment by daimz** [comment]
Thanks for that @sudharsanmit really helpful!

**Comment by daimz** [comment]
@sudharsanmit I am using the method you suggested above, but I am running into an error and wondering if you could help me with it.
I have created the service as you suggested but I now have to services a `cohort.service` and a `team.service` in both services I am needed to access my secondary database so I have included the `CoreDB.service` and then initiated in both services. This returns the following error `FirebaseError {code: "app/duplicate-app", message: "Firebase: Firebase App named 'core' already exists (app/duplicate-app).", name: "core", ngDebugContext: DebugContext_, ngErrorLogger: ƒ, …}`

I realise this is because I am now attempting to initialise my secondary database twice. How can I do this at a root level or similar so that it is only initiated once but available to all my services?

Here's what my code looks like:
*teams.service*
```
export class TeamsService {
  private sdkDb;
  private app;
  private teamsRef;

  constructor(
    private db: AngularFireDatabase,
    private coreDB: CoreDBService
  ) {
    coreDB.init(environment.fbCoreConfig);
    console.log(coreDB.app);
    const ref = coreDB.app.database().ref('/teams');
    this.teamsRef = ref;

    this.sdkDb = firebase.database().ref();
  }
```

*cohort.service*
```
export class CohortsService {
  private sdkDb;
  private core;
  private teamsRef;
  private cohortSubject: Subject<Cohort> = new Subject();

  constructor(
    private db: AngularFireDatabase,
    private feedsService: FeedsService,
    private http: Http,
    private coreDB: CoreDBService
  ) {
    coreDB.init(environment.fbCoreConfig);
    console.log(coreDB.app);
    this.core = coreDB.app;
    this.sdkDb = firebase.database().ref();
  }
```

*CoreDB.service:*
```
import {Injectable,Inject} from '@angular/core';
import * as firebase from 'firebase/app';
import { AngularFireDatabase, FirebaseListObservable, FirebaseObjectObservable } from 'angularfire2/database';


@Injectable()
export class CoreDBService {
  core:any;
  app;
  constructor (private db: AngularFireDatabase){}

  init(config){
    this.app = firebase.initializeApp(config, "core");
    const ref = this.app.database().ref('/teams');
    const listObs = this.db.object(ref);
    listObs.subscribe(data => console.log(data));
  }
}
```

**Comment by sudharsanmit** [comment]
I used "secondary" instead of "core" here. Wonder if that makes a difference.


this.app = firebase.initializeApp(config, "*core*");

**Comment by sudharsanmit** [comment]
I used this link as reference - https://firebase.google.com/docs/configure/

**Comment by sudharsanmit** [comment]
Btw, your usage is wrong. You are trying to connect to same DB again, that
is why you are getting the duplicate error. My example is to connect to a
second database which has different config than the primary (default) DB.

**Comment by daimz** [comment]
No I want to use `core` in both the services, turns out what I did have wrong was having `coreDB.init(environment.fbCoreConfig);` in both cohorts.service and teams.service this effectively was telling firebase to initialize the `core` database twice. 

I manage to resolve the error by moving `coreDB.init(environment.fbCoreConfig);` to my root.component (app.component for most setups) I could then still use the coreDb.service to access my database in the cohorts and teams services like this:
`this.core = coreDB.app;`

Now I can switch between the default database and my `core` database but including my coredb.service and I only initiate the database once.

Thanks for all the help!

**Comment by JumpLink** [comment]
How can I get his working if I want to define the app name on my imports?

```
@NgModule({
...
  imports: [
    AngularFireModule.initializeApp(environment.firebase, 'my-name'),
  ],
```

With `my-name` I get an error: `No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).`

**Comment by sasxa** [comment]
I'm also interested in this feature. I looked over a source code and as far as I can tell `app` is only initialized in the constructor of top level classes: database, auth, firestore:

```typescript

export class AngularFireDatabase {
  constructor(public app: FirebaseApp) {
    this.database = app.database();
  }
}
```

@davideast Would it be possible to add an option to switch apps in these classes (`AngularFireDatabase`, `AngularFireAuth`, etc.)? For example:

```typescript
export class AngularFireDatabase {
  constructor(public app: FirebaseApp) {
    this.database = this.connect(app);
  }

  connect(app: FirebaseApp) { // might need a better name
    return app.database()
  }
}
```
Then we could use it:

```typescript
export class AppComponent {
  constructor(db: AngularFireDatabase) {
    // using default app from AngularFireModule.initializeApp(...)
  }
}
export class OtherComponent {
  constructor(db: AngularFireDatabase) {
     db.connect(firebase.initializeApp(new_config))
    // using new app
  }
}
```
---
Or can this be achieved with:
```typescript
export class MultiAppAngularFireDatabase extends AngularFireDatabase {
  connect(app: FirebaseApp) {
    return (app || this.app).database()
  }
}

@NgModule({
  imports: [
    AngularFireModule.initializeApp(...)
  ],
  providers: [
    { provide: AngularFireDatabase, useClass: MultiAppAngularFireDatabase },
    { provide: AngularFireAuth , useClass: MultiAppAngularFireAuth  },
    ...
  ],
})
```
I'm not sure if `app` is used somewhere else in code directly (in which case this wouldn't work)...

**Comment by 47sharmamanu** [comment]
Where is"firebase" import used in:

firebase.initializeApp(config, "name");

**Comment by james11a** [comment]
Hope this helps.

My solution is implemented in Ionic application that I am working on. I have 2 Firebase projects so that I can connect to 2 separate databases. Google charges for having multiple databases in the same Firebase project. Below is my configuration:

Say the 2 Firebase application configuration variables are **firebaseConfigA** & **firebaseConfigB** with their names '*appA*' & '*appB* ' stored in **firebaseAppNameA** & **firebaseAppNameB**.

*Note:* It is recommended that all such configuration variables are stored in a separate configuration file / custom webpack environment files. The variables will be imported wherever required from here. In my case, I have custom webpack environment setup.
If you need help with setting up environments using custom webpack for Ionic, check out this fantastic post from @gshigeto: https://github.com/gshigeto/ionic-environment-variables

Anyway, to the code...

> app.module.ts
```
import { firebaseConfigA, firebaseAppNameA } from "@app/env";
import { AngularFireModule } from "angularfire2";
import { AngularFireDatabaseModule, AngularFireDatabase } from "angularfire2/database";

@NgModule({
    declarations: [ ... ],
    imports: [
        ...
        AngularFireModule.initializeApp(firebaseConfigA, firebaseAppNameA),
        AngularFireDatabaseModule
    ],
    bootstrap: [IonicApp],
    entryComponents: [ ... ],
    providers: [
        ...
        AngularFireDatabase
    ]
})
```

All my Firebase related function are handled in a separate service:
> firebase.service.ts
```
/** Angular imports */
import { Injectable } from "@angular/core";

/** 3rd-party imports */
import {
    AngularFireDatabase, _getAngularFireDatabase,
    AngularFireList, AngularFireObject
} from "angularfire2/database";
import { FirebaseAppConfig } from "angularfire2";
import * as firebase from "firebase/app";

@Injectable()
export class FirebaseService {
    private _db: AngularFireDatabase;

    constructor() { }

    /** Function to initialize firebase application and
     * get DB provider for the corresponding application.
     * If Firebase app is already initialized, skip initialization and
     * return DB provided for the app
     */
    public initFirebaseApp(config: FirebaseAppConfig, firebaseAppName: string) {
        let initializedFBApps: string[] = [];
        firebase.apps.forEach(app => {
            initializedFBApps.push(app.name);
        });

        if (initializedFBApps.indexOf(firebaseAppName) === -1) {
            firebase.initializeApp(config, firebaseAppName);
        }

        this._db = _getAngularFireDatabase(firebase.app(firebaseAppName));
    }

    /** Function to get firebase DB list */
    public getList(path: string): AngularFireList<{}> {
        return this._db.list(path);
    }

    /** Function to get firebase DB object */
    public getObject(path: string): AngularFireObject<{}> {
        return this._db.object(path);
    }
}
```
Now, using the service in a component where I connect to both applications:
> home.component.ts
```
// ... do all required imports
import {
    firebaseConfigA, firebaseAppNameA,
    firebaseConfigB, firebaseAppNameB
} from "@app/env";
import { FirebaseService } from "../../services/firebase.service";

@Component({
    selector       : "page-home",
    templateUrl    : "home.html"
})
export class ScannerDemoPage implements OnInit {
    constructor(private _firebaseService: FirebaseService) { }
    
    ngOnInit() {
        // Initialize 1st application
        this._firebaseService.initFirebaseApp(firebaseConfigA, firebaseAppNameA);
        let myList = this._firebaseService.getList("/path1");

        // Initialize 2nd application
        this._firebaseService.initFirebaseApp(firebaseConfigB, firebaseAppNameB);
        let myObj = this._firebaseService.getObject("/path2");
    }
}
```

You don't need to worry about re-initializing the Firebase application in multiple components as the ```initFirebaseApp()``` function in ```firebase.service.ts``` handles avoiding re-initialization of application and sets only the DB provider if the application is already initialized.

**Comment by texano00** [comment]
Hi @davideast 

i've supposed that `af` is of type AngularFireDatabase but `af.database.list` doesn't exist.

Thanks
