### ISSUE TITLE
Disable/remove user account from other user via angularfire2 with firebaseApp

### ISSUE THREAD

**Issue by ivytruong** [angular/angularfire2#764]
I am very new to the angular2 as well as firebase and currently involving in a project that is using them. I want to build a web app that contains the relationship between managers and the employees. The managers here can remove and add the user on a managing employees interface. 

I looked through the post of others and see that there are functions that had not been released yet in angularfire2 and need to use the old library (FirebaseApp). However, I could not find any documentation on all functions in the library (the only one I ever saw is database.sendPasswordResetEmail(Val)).

I wonder if anyone gives me the documentation on the library? 

Or Is there any way that I can disable/remove a user (employee) from the hand of another user (manager) without just setting "Inactive" properties in the database?

FYI: The project is using the newest version of angular2 and angularfire2

**Comment by katowulf** [comment]
All issues have to follow the issue template provided. I understand this is asking a lot and is generally annoying when you feel your question is straightforward, but just trust that it's critical to keep things streamlined and manageable for our team. I'm closing this for now because it doesn't adhere to these requirements. Feel free to resubmit according to the template, being absolutely sure to include a working, minimal repro of the problem and version info. Note that how-to questions are better suited for Stack Overflow or a discussion group.

To give you some starting references here:  Role-based security isn't managed via the Authentication tools. Instead, you would store the relationships between users in your Database and use security rules (not authentication credentials) to do this. There may be more tools for this in the future but that's not currently the mechanism for this sort of activity. Nor is this related to AngularFire, but to the underlying Firebase SDKS. See also [admin SDKS](https://firebase.google.com/docs/admin/setup).
