### ISSUE TITLE
Getting nested key from Firebase Data

### ISSUE THREAD

**Issue by fearless23** [angular/angularfire2#780]
My Firebase Data is follows 
![firebase](https://cloud.githubusercontent.com/assets/2442744/22114712/773bed58-de90-11e6-9839-3a352b8894d4.png)

I am using Angular2 + Firebase

from activatedRoute in my application i get unique id -Kar2tyvPZcu15y_1bWF

now i want to get that object

CODE::
```

      export class MyProjectComponent {
        sub: any;
        db;
        project;
        constructor( private route: ActivatedRoute, af: AngularFire) {
          this.route = route;
          this.db = af.database.list('projects');
          console.log("Database " + this.db);
        }
      
        ngOnInit() {

          this.sub = this.route.params.subscribe(params => {
          let id = params['id'];
          console.log("ID " +id);
        });

        this.db.map( projects => {
          const filtered = projects.filter(project => project.uid=== '-KamS40N02VGAZmmRWBF');
          console.log("Filtered "+filtered);
          this.project = filtered;  })

        }


      }
``` 
But this is not working, even console.log not outputting anything.

Basically based on a UID, i want to grab an object which is nested 2 levels deep,
my object can be in projects/base or projects/personal or projects/pro or projects/social

For single level depth its good: i can use af.database.list('projects/base/${UID}'); but i dont know where is my object i can be in either of base,personal,pro,social which are child of projects...

I can flatten my data Structure, but still how to get this done...

**Comment by katowulf** [comment]
All issues have to follow the issue template provided. I understand this is asking a lot and is generally annoying when you feel your question is straightforward, but just trust that it's critical to keep things streamlined and manageable for our team. I'm closing this for now because it doesn't adhere to these requirements. Feel free to resubmit according to the template, being absolutely sure to include a working, minimal repro of the problem and version info. 

Note that how-to questions like this one are better suited for Stack Overflow or a discussion group.
