### ISSUE TITLE
Promises with login() doesn't work

### ISSUE THREAD

**Issue by fonzy2013** [angular/angularfire2#784]
### Version info

**Angular:**
2.3.1
**Firebase:**
3.6.5
**AngularFire:**
2.0.0-beta.7
**Other (e.g. Ionic/Cordova, Node, browser, operating system):**
Mac OS X
### How to reproduce these conditions
Use any example, https://blog.khophi.co/angularfire2-authentication/ for instance and and see the logs when login().then(...) is called.

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**
Can provide one if needed

**Steps to set up and reproduce**
Add logic to this.af.auth.login().then() to see that the promise is never triggered, nor is the catch.
Example:
```javascript
loginGoogle() {
    this.af.auth.login({
      provider: AuthProviders.Google,
      method: AuthMethods.Redirect
    }).then(
      (success) => {
        console.log(success);
        this.router.navigate(['/dashboard']);
      }).catch(
      (err) => {
        console.log(err);
        this.router.navigate(['/dashboard']);
      })
  }
```

**Sample data and security rules**

<-- include/attach/link to some json sample data (or provide credentials to a sanitized, test Firebase project) -->

### Debug output

** Errors in the JavaScript console **
Nothing
** Output from `firebase.database().enableLogging(true);` **

** Screenshots **

**Comment by fonzy2013** [comment]
Another note is that I tried with the following with the same result:
```
  loginWithObservable() {
    Observable.fromPromise(
      <Promise<any>>this.af.auth.login())
      .do(
        function (x) { console.log('Do Next:', x); }, 
        function (err) { console.log('Do Error:', err); }, 
        function () { console.log('Do Completed'); }
        ).subscribe()
  }
```

**Comment by davideast** [comment]
Two things. 

1. Have you enabled Google Login in the Firebase Console?
2. Avoid using the promise resolution from `.login()` in favor of the auth observable.

```ts
this.af.auth.subscribe(auth => console.log);
```

**Comment by fonzy2013** [comment]
1. Yes
2. I do that as well but in this case I need to as I need to route to another route.

**Comment by fonzy2013** [comment]
I will elaborate on why I think this is an issue.
- The `this.af.auth.login())` is commonly used on a login route and after a successful login the user should be routed to a main route. 
- The  `this.af.auth.subscribe()` is called on any changes meaning that a call to route to main will happen several (unwanted) times.

**Comment by DennisSmolek** [comment]
Yeah the longer you leave the auth Observable running the more you can see it firing for no reason. We added a `_firstLoad` to protect against it.. We use the auth Observable though because we allow our users to stay logged in/have more tabs open which if you have to route from the `.login()` call you'd miss..

**Comment by fonzy2013** [comment]
Does this mean the promise will be removed from login()?

**Comment by bdrelling** [comment]
Jumping in here because I'm confused at the optimal way to handle this as well. It makes sense to me that the `af.auth.login` promise can't return in a redirect, because you're leaving the page before this can fire on `AuthMethods.Redirect`, but how can we handle this appropriately? I don't see anything in `FirebaseAuthState` that will help me navigate when returning, tell me it's a first-time authentication of a new user other than checking the `uid` against my table, or any way to pass in the redirect route to return the user to the page they were viewing.

I'm not sure if I'm missing something, but I've dug into the routes that are exposed via the definition and checked the docs. I'm about to jump into the source but I'm not sure I'll get the answers. Apologies if I'm blind, but I just don't understand how to handle this properly. I feel like what I'm doing right now is really hacky.

Ultimately, I'd also like to know if this is a bug or if there's a confirmed best practice for handling all of the events in this issue.

**Comment by fonzy2013** [comment]
Is anyone looking into this?

**Comment by davideast** [comment]
@fonzy2013 See #854 for the `rc0` proposal. It removes the login feature and relies on the SDK.
