### ISSUE TITLE
Is there any way to check if im online or not using AF2?

### ISSUE THREAD

**Issue by AhadCove** [angular/angularfire2#797]
I want to be able to check if im online or not and go through two different paths corresponding to the result. 
I know Firebase made a way for presense, but would I be able to use it in AF2? And how would I be able to?

**Comment by katowulf** [comment]
All issues have to follow the issue template provided. I understand this is asking a lot and is generally annoying when you feel your question is straightforward, but just trust that it's critical to keep things streamlined and manageable for our team. I'm closing this for now because it doesn't adhere to these requirements. Feel free to resubmit according to the template, being absolutely sure to include a working, minimal repro of the problem and version info. 

Note that how-to questions are better suited for Stack Overflow or a discussion group.
