### ISSUE TITLE
Facebook login returns accessToken

### ISSUE THREAD

**Issue by jacobo3d** [angular/angularfire2#806]
When signing in with Facebook, sometimes I get an object with the user information (name, photoUrl, uid, etc...), and other times an object with an accessToken (made sure the user was signed out). I'm not sure exactly why that happens. 

This is the code I'm using:

```
this.auth$.login({
        provider: AuthProviders.Facebook,
        method: AuthMethods.Redirect
      });
```

Thanks!

**Comment by JasonGoemaat** [comment]
Might be linked to #805 I created a few hours before yours, it seems like the 'credentials' with the accessToken only comes through on the login call.  My guess is that once firebase auths the user with the login they don't store the facebook access token for security reasons but I'm not sure.

**Comment by jacobo3d** [comment]
Thanks for replying. I totally missed [#805](https://github.com/angular/angularfire2/issues/805), I must have left the issue page open for a while and sent mine before even refreshing.
In my case both redirecting or using popup behaves in the same way. I'll keep an eye on both issues to see if somebody can cast some light on this. Cheers!

**Comment by davideast** [comment]
Closing this for discussion in #805.

**Comment by MartinNuc** [comment]
Are you sure its the same thing as #805 ?

#805 is feature request to be able to get an access token while this one looks like a bug.

I actually came here because I am having the same issue:

I subscribe to `auth: AngularFireAuth`. After I log in / log out few times I start to get a different response. First few logins contains user's information in `value.facebook` (name, photoUrl, uid, etc...) but after a few logins/logouts there is only `accessToken` but no user's information. This is rather inconsistent behaviour.

I can see user's info under `authObject.auth.providerData[0]`.

I am using:

```
export const myFirebaseAuthConfig = {
  provider: AuthProviders.Facebook,
  method: AuthMethods.Popup
};
```
