### ISSUE TITLE
Authentication with Facebook provider results in "popup has been closed by user" error

### ISSUE THREAD

**Issue by gabosvk** [angular/angularfire2#842]
### Version info

**Angular:** 2.4.1

**Firebase:** 3.4.0

**AngularFire:** ^2.0.0-beta.8

**Other (e.g. Ionic/Cordova, Node, browser, operating system):** OS - macOS Siera - 10.12.3, Browser: Safari 10.0.3, Node: v7.4.0.

### How to reproduce these conditions

**Failing test unit, Plunkr, or JSFiddle demonstrating the problem**

**Steps to set up and reproduce**

I'm trying to make an authentication using Facebook provider with Popup method in Safari. Once I start the authentication a new tab is opened where a facebook authentication is ongoing. After few seconds (2 - 3) the whole process gets stuck for couple of more seconds (5 - 8) and after the popup is closed and my original page is shown and I a see an error message in console saying that the popup has been closed. Just reminding I'm not closing that popup manually, nor do any other activity. 
This is not happening in other browsers (Firefox, Chrome), nor with Google provider (Google provider is working on Safari as well).

### Debug output

** Errors in the JavaScript console **
`R {code: "auth/popup-closed-by-user", message: "The popup has been closed by the user before finalizing the operation.", G: function}`

** Output from `this._angularFire.auth.login({
                provider: AuthProviders.Facebook,
                method: AuthMethods.Popup
            });` **

### Expected behavior

Working login with Facebook provider on Safari.

### Actual behavior
Not working login with Facebook provider on Safari. 

Please, let me know if I can provider more details. Thanks.

**Comment by davideast** [comment]
@gabosvk Can you create a plnkr so it's easier to debug?

**Comment by lucapale** [comment]
Same problem here, but it seems to be a problem of Firebase and not AngularFire.
On Safari I can login only through redirect and not through Popup.

**Comment by numerized** [comment]
Hi @davideast, Hi all.

I have all the latest versions installed. Firebase, angularFire, ionic3.0.1

Regarding this problem (or not exactly the same, if you need me to open a new Issue I'd be happy to do so as long as I have seen this problem for one year and our target use is exactly the one described below)

There's a really weird thing happening when you log-in to a firebase app from inside the in-app facebook browser only in IOS environments. Android and Web is working perfectly on all browsers.

This bug is only on iOS from facebook app and Facebook Messenger.
On Android all is working like expected inside messenger and inside facebook in-app browsers.

To try it : 

1-Simply open facebook app
2-Search for Utoopie page
3-scroll down and look for a post that redirects to our web-app like this one:

[SONDAGE]
D'après vous, si Mélenchon passe au 2e tour des élections 2017, qui sera son adversaire ?
Pour participer c'est ici : http://beta.utoopie.com/pie/-Kh3TjDaAaIzrlaAwXGv/8734093724
....

4-Visit the link
5-It'll open the facebook in-app web browser
6-Cast a vote with any of the button under the question.
7-It'll open a modal : Click on the button that says Facebook 
8-It'll show a white page and then nothing.

This problem behaviour is quite common in other tools but I've never seen any issue reported here.
https://github.com/sahat/satellizer/issues/674

Thanks a lot !

**Comment by numerized** [comment]
Sorry I had to remove FB angularfire2 authentication because if people are coming from facebook they cannot login. It's a real problem for platform that rely on sharing deep content.

**Comment by shaagi** [comment]
Why is this issue closed? It's still a problem. When opened via fb messenger, snapchat, instagram it doesn't let the user login if their using an iPhone just like @numerized mentioned.
